### ISSUE TITLE
An error was thrown in afterAll  Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by snowfrogdev** [testing-library/angular-testing-library#244]
I get the following error when trying to run tests using angular-testing-library:

In the karma chrome test runner: 
```bash
Error during loading: Uncaught ReferenceError: process is not defined in http://localhost:9876/_karma_webpack_/vendor.js line 111178
```

![image](https://user-images.githubusercontent.com/22530235/132256627-e90df5c9-7238-4a50-ae4e-05bde13af515.png)

In the terminal:
```bash
Chrome 92.0.4515.159 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: process is not defined
  ReferenceError: process is not defined
      at Module.14077 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@testing-library/angular/__ivy_ngcc__/fesm2015/testing-library-angular.js:241:1)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.39224 (http://localhost:9876/_karma_webpack_/main.js:81:82)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at webpackContext (http://localhost:9876/_karma_webpack_/webpack:/projects/property-owner/src|sync|/.spec/.ts$:9:1)
      at Array.map (<anonymous>)
      at Module.11778 (http://localhost:9876/_karma_webpack_/webpack:/projects/property-owner/src/test.ts:20:16)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at http://localhost:9876/_karma_webpack_/webpack:/webpack/startup:4:84
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:25:1)
```

It looks like it's trying to run Node specific code in the browser and since there is no `process` property on the  global or window object in the browser, it fails. I don't understand why it is trying to do that though.

Any help will be greatly appreciated.

**Comment by timdeschryver** [comment]
Hi @snowfrogdev which version of Angular Testing Library are you using?
If you're not on v10.11.0, could you try to upgrade it. I thought we had this fixed in one of our latest releases.

**Comment by snowfrogdev** [comment]
I had v10.3.0. I upgraded to v10.11.0 and that seems to have fixed it.
Thanks a bunch.

**Comment by timdeschryver** [comment]
Great to hear that, thanks for the update @snowfrogdev
