### ISSUE TITLE
How can I debug rendering a component with many nested subcomponents?

### ISSUE THREAD

**Issue by cesalberca** [testing-library/angular-testing-library#58]
Hello! I'm trying to render a component that has many subcomponents, and some of those components have services being injected. I've gone through all the components and mocked all the dependencies.

```typescript
describe('PageContainer', () => {
  it('should navigate back when clicking on back', async () => {
    const component = await setup()

    console.log(component)
  })
})

async function setup() {
  const installationStore = mock(InstallationStore)
  when(installationStore.getActiveInstallation()).thenReturn(EMPTY)
  when(installationStore.get()).thenReturn(EMPTY)
  const changeActiveInstallationUseCase = mock(ChangeActiveInstallationUseCase)
  when(changeActiveInstallationUseCase.execute(anything())).thenResolve()
  const window = mock<Window>()
  const component = await render(PageContainer, {
    declarations: [
      PageComponent,
      InstallationSwitcherComponent,
      EnergeticRoleIconComponent,
      ModalComponent,
      BarComponent,
      IconComponent
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    imports: [TranslateTestingModule],
    componentProviders: [
      {
        provide: InstallationStore,
        useValue: instance(installationStore)
      },
      {
        provide: ChangeActiveInstallationUseCase,
        useValue: instance(changeActiveInstallationUseCase)
      }
    ],
    providers: [
      {
        provide: WINDOW_TYPE,
        useValue: instance(window)
      }
    ]
  })
  return component
}
```

However, I'm probably missing a subcomponent's dependency –although I've been looking like crazy– and I get this cryptic error:

```
TypeError: function is not iterable (cannot read property Symbol(Symbol.iterator))

    at new Set (<anonymous>)
    at _ValueOutputAstTransformer.visitStringMap (/Users/redacted/packages/compiler/src/output/value_util.ts:29:23)
    at visitValue (/Users/redacted/packages/compiler/src/util.ts:40:20)
    at convertValueToOutputAst (/Users/redacted/packages/compiler/src/output/value_util.ts:18:10)
    at singleProviderDef (/Users/redacted/packages/compiler/src/view_compiler/provider_compiler.ts:116:22)
    at providerDef (/Users/redacted/node_modules/@angular/compiler/bundles/compiler.umd.js:22024:13)
    at /Users/redacted/packages/compiler/src/ng_module_compiler.ts:38:62
    at Array.map (<anonymous>)
    at NgModuleCompiler.compile (/Users/redacted/packages/compiler/src/ng_module_compiler.ts:38:44)
    at JitCompiler._compileModule (/Users/redacted/packages/compiler/src/jit/compiler.ts:153:52)
    at /Users/redacted/packages/compiler/src/jit/compiler.ts:119:31
    at Object.then (/Users/redacted/packages/compiler/src/util.ts:89:74)
    at JitCompiler._compileModuleAndAllComponents (/Users/redacted/packages/compiler/src/jit/compiler.ts:115:22)
    at JitCompiler.compileModuleAndAllComponentsSync (/Users/redacted/packages/compiler/src/jit/compiler.ts:65:38)
    at CompilerImpl.compileModuleAndAllComponentsSync (/Users/redacted/packages/platform-browser-dynamic/src/compiler_factory.ts:61:35)
    at TestingCompilerImpl.compileModuleAndAllComponentsSync (/Users/workspace/packages/platform-browser-dynamic/testing/src/compiler_factory.ts:52:27)
    at TestBedViewEngine._initIfNeeded (/Users/workspace/packages/core/testing/src/test_bed.ts:376:28)
    at TestBedViewEngine.createComponent (/Users/workspace/packages/core/testing/src/test_bed.ts:570:10)
    at Function.TestBedViewEngine.createComponent (/Users/workspace/packages/core/testing/src/test_bed.ts:232:36)
    at createComponentFixture (/Users/redacted/node_modules/@testing-library/angular/bundles/ng:/@testing-library/angular/lib/testing-library.ts:124:18)
    at Object.<anonymous> (/Users/redacted/node_modules/@testing-library/angular/bundles/ng:/@testing-library/angular/lib/testing-library.ts:64:19)
    at step (/Users/redacted/node_modules/tslib/tslib.es6.js:97:23)
    at Object.next (/Users/redacted/node_modules/tslib/tslib.es6.js:78:53)
    at /Users/redacted/node_modules/tslib/tslib.es6.js:71:71
    at new ZoneAwarePromise (/Users/redacted/node_modules/zone.js/dist/zone.js:931:29)
    at __awaiter (/Users/redacted/node_modules/tslib/tslib.es6.js:67:12)
    at Object.render (/Users/redacted/node_modules/@testing-library/angular/bundles/testing-library-angular.umd.js:377:16)
    at /Users/redacted/src/app/features/installation/ui/page.container.spec.ts:32:27
    at Generator.next (<anonymous>)
    at /Users/redacted/node_modules/tslib/tslib.js:110:75
    at new ZoneAwarePromise (/Users/redacted/node_modules/zone.js/dist/zone.js:931:29)
    at Object.__awaiter (/Users/redacted/node_modules/tslib/tslib.js:106:16)
    at setup (/Users/redacted/src/app/features/installation/ui/page.container.spec.ts:26:20)
    at Object.<anonymous> (/Users/redacted/src/app/features/installation/ui/page.container.spec.ts:19:29)
    at Generator.next (<anonymous>)
    at /Users/redacted/node_modules/tslib/tslib.js:110:75
    at new ZoneAwarePromise (/Users/redacted/node_modules/zone.js/dist/zone.js:931:29)
    at Object.__awaiter (/Users/redacted/node_modules/tslib/tslib.js:106:16)
    at /Users/redacted/src/app/features/installation/ui/page.container.spec.ts:18:63
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/Users/redacted/node_modules/zone.js/dist/zone.js:391:26)
    at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (/Users/redacted/node_modules/zone.js/dist/proxy.js:129:39)
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/Users/redacted/node_modules/zone.js/dist/zone.js:390:52)
    at Zone.Object.<anonymous>.Zone.run (/Users/redacted/node_modules/zone.js/dist/zone.js:150:43)
    at Object.<anonymous> (/Users/redacted/node_modules/jest-preset-angular/zone-patch/index.js:52:27)
    at Object.asyncJestTest (/Users/redacted/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/redacted/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (<anonymous>)
    at mapper (/Users/redacted/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/redacted/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I know the existence of the `debug` function for a component, but this only works **once the component is rendered**. Is there any way I can debug when the component is trying to render initially easily and look for the missing sub dependency? I've tried setting breakpoints but it's so difficult to navigate through the `testing-library-angular.umd.js` file.

**Comment by timdeschryver** [comment]
This might be an issue with the setup of the DI in this library.
Have you tried using the same setup with an Angular TestBed?

**Comment by timdeschryver** [comment]
Closing due to inactivity, feel free to open a new issue.
