### ISSUE TITLE
[First Time User] testing.TestBed.inject is not a function

### ISSUE THREAD

**Issue by dereklin** [testing-library/angular-testing-library#83]
I am trying to understand how this library works.

My code looks like:

```
@Component({
  template: `
      <app-my-wrapper
          [someProp]="true"
          (someAction)="handleAction()"
      >
          <app-my-component
              [someProp]="myProp"
              (someAction)="handleComponentAction($event)"
          ></app-my-component>
      </app-my-wrapper>
  `
})
class TestComponent {
  @ViewChild(MyComponent, { static: true }) myComponent: MyComponent;
  myProp = 'myProp';
  public handleComponentAction(evt) {}

  public handleAction() {
  }
}

describe('angular testing library', () => {
  it('trying out angular testing library for the first time', async () => {
      const { getByText } = await render(TestComponent, { imports: [MyTestingModule, MyModule] });

      expect(getByText('Current Count: 5'));
  });
});
```

I get:

```
TypeError: testing.TestBed.inject is not a function

      at Object.<anonymous> (node_modules/@testing-library/angular/bundles/ng:/@testing-library/angular/lib/testing-library.ts:114:24)
      at step (node_modules/tslib/tslib.es6.js:99:23)
      at Object.next (node_modules/tslib/tslib.es6.js:80:53)
      at fulfilled (node_modules/tslib/tslib.es6.js:70:58)
```

Could you point out my mistakes in the code?

**Comment by timdeschryver** [comment]
Hey @dereklin , what version of Angular and Testing Library are you using?

**Comment by dereklin** [comment]
@timdeschryver Thanks for the hint!  I am using angular 8x.  Using @testing-library/angular@8.2.0 solves my problem.  I really like when the test fails, I get to see the html template along with the error.  That is so helpful!

Do you know if there is an even easier way for me to set up my test, like not having to create the TestComponent?

**Comment by timdeschryver** [comment]
Awesome, glad we could resolve this quickly :)

I think the following example is what you're looking for
https://github.com/testing-library/angular-testing-library/blob/master/src/app/examples/02-input-output.spec.ts
